// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbibmeutwfqpgwgqzdgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiaWJtZXV0d2ZxcGd3Z3F6ZGdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzE4NTgsImV4cCI6MjA2MjM0Nzg1OH0.BonwWws1pufLi3PsYknxEYNx9QLcHfuun70ZWBJQOQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);